### ISSUE TITLE
Daphne doesn't work on ubuntu

### ISSUE THREAD

**Issue by sidprobstein** [sidprobstein/swirl-search#54]
$ daphne
Traceback (most recent call last):
  File "/home/sid/.local/bin/daphne", line 5, in <module>
    from daphne.cli import CommandLineInterface
  File "/home/sid/.local/lib/python3.10/site-packages/daphne/cli.py", line 10, in <module>
    from .server import Server
  File "/home/sid/.local/lib/python3.10/site-packages/daphne/server.py", line 36, in <module>
    from twisted.internet.endpoints import serverFromString
  File "/home/sid/.local/lib/python3.10/site-packages/twisted/internet/endpoints.py", line 63, in <module>
    from twisted.python.systemd import ListenFDs
  File "/home/sid/.local/lib/python3.10/site-packages/twisted/python/systemd.py", line 18, in <module>
    from attrs import Factory, define
ModuleNotFoundError: No module named 'attrs'

**Comment by sidprobstein** [comment]
Installation issue. Can't reproduce.
