### ISSUE TITLE
Server Error 500 when Patch-ing a SearchProvider

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#74]
To reproduce:
- Go to an individual Search Provider Instance page (e.g. http://localhost:8000/swirl/searchproviders/1/)
- Select the "Raw data" tab
- Select the "Patch" option (you don't need to make a config change)
- You should get the Server Error 500

From the `django.log` file:
```
2022-12-10 16:48:59,996 ERROR    Internal Server Error: /swirl/searchproviders/1/
Traceback (most recent call last):
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/erikspears/.pyenv/versions/3.9.9/lib/python3.9/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
TypeError: update() got an unexpected keyword argument 'partial'
```

**Comment by sidprobstein** [comment]
Deferred
