### ISSUE TITLE
Docker shutdown / restart issue with v. 1.8 Swirl?

### ISSUE THREAD

**Issue by erikspears** [sidprobstein/swirl-search#90]
It appears that doing a ctrl-c to gracefully stop Docker (MacOS, Terminal) doesn't result in rabbitmq being properly terminated ... or, in the shutdown process not fully clearing or deleting the `.swirl` file.

To see this in action:
- Get the Docker version of Swirl 1.8 up and running (do a search to make sure, etc.)
- Issue `CTRL-C` in the Terminal window where you ran `docker compose up`
- Give it a moment or few to finish shutdown, then issue a fresh `docker compose up`
- You'll see this warning about rabbitmq running already:
```
swirl1-8rc-app-1  | Error: rabbitmq appears to be running, please check .swirl or remove it; exiting...
swirl1-8rc-app-1  | Command start reported an error
```

- Docker will continue to bring up Swirl
- Once it's up, do a search (e.g. `?q=tesla`)
- You will get this rather gnarly error in the results window along with a mighty stacktrace:
```
OperationalError at /swirl/search/
[Errno 111] Connection refused
```

To remediate this issue:

- While Docker is still running
- Go the the Docker GUI, Containers > open the container in question > three-dot menu > Open in Terminal
- Remove the `.swirl` file
- Stop Docker
- Restart Docker

Screen grab of the rabbitmq error when starting Docker:
![Docker - 1 8 shut down](https://user-images.githubusercontent.com/98238295/212562408-af3b0ccc-f2d8-4ea8-908c-d0ab04b834e0.png)

Screen grab of Operational Error in the UI:
![Docker - 1 8 restart error](https://user-images.githubusercontent.com/98238295/212562423-050fa78e-374e-4dfe-9a13-3187ddb786d5.png)

The might stack from the Terminal window where Docker was running:
```
swirl1-8rc-app-1  | 2023-01-15 14:10:41,744 INFO     views.py: Search.create() from ?q
swirl1-8rc-app-1  | Internal Server Error: /swirl/search/
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 30, in __call__
swirl1-8rc-app-1  |     return self.__value__
swirl1-8rc-app-1  | AttributeError: 'ChannelPromise' object has no attribute '__value__'
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | During handling of the above exception, another exception occurred:
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
swirl1-8rc-app-1  |     yield
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 433, in _ensure_connection
swirl1-8rc-app-1  |     return retry_over_time(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
swirl1-8rc-app-1  |     return fun(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 877, in _connection_factory
swirl1-8rc-app-1  |     self._connection = self._establish_connection()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 812, in _establish_connection
swirl1-8rc-app-1  |     conn = self.transport.establish_connection()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
swirl1-8rc-app-1  |     conn.connect()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 323, in connect
swirl1-8rc-app-1  |     self.transport.connect()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 129, in connect
swirl1-8rc-app-1  |     self._connect(self.host, self.port, self.connect_timeout)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 184, in _connect
swirl1-8rc-app-1  |     self.sock.connect(sa)
swirl1-8rc-app-1  | ConnectionRefusedError: [Errno 111] Connection refused
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | The above exception was the direct cause of the following exception:
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
swirl1-8rc-app-1  |     raise exc_info[1]
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 42, in inner
swirl1-8rc-app-1  |     response = await get_response(request)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
swirl1-8rc-app-1  |     response = await wrapped_callback(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 448, in __call__
swirl1-8rc-app-1  |     ret = await asyncio.wait_for(future, timeout=None)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
swirl1-8rc-app-1  |     return await fut
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 22, in run
swirl1-8rc-app-1  |     result = self.fn(*self.args, **self.kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 490, in thread_handler
swirl1-8rc-app-1  |     return func(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
swirl1-8rc-app-1  |     return view_func(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
swirl1-8rc-app-1  |     return self.dispatch(request, *args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
swirl1-8rc-app-1  |     response = self.handle_exception(exc)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
swirl1-8rc-app-1  |     self.raise_uncaught_exception(exc)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
swirl1-8rc-app-1  |     raise exc
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
swirl1-8rc-app-1  |     response = handler(request, *args, **kwargs)
swirl1-8rc-app-1  |   File "/app/swirl/views.py", line 191, in list
swirl1-8rc-app-1  |     search_task.delay(new_search.id)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 425, in delay
swirl1-8rc-app-1  |     return self.apply_async(args, kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
swirl1-8rc-app-1  |     return app.send_task(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 788, in send_task
swirl1-8rc-app-1  |     amqp.send_task_message(P, name, message, **options)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 510, in send_task_message
swirl1-8rc-app-1  |     ret = producer.publish(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
swirl1-8rc-app-1  |     return _publish(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 523, in _ensured
swirl1-8rc-app-1  |     return fun(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 186, in _publish
swirl1-8rc-app-1  |     channel = self.channel
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 209, in _get_channel
swirl1-8rc-app-1  |     channel = self._channel = channel()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 32, in __call__
swirl1-8rc-app-1  |     value = self.__value__ = self.__contract__()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 225, in <lambda>
swirl1-8rc-app-1  |     channel = ChannelPromise(lambda: connection.default_channel)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 895, in default_channel
swirl1-8rc-app-1  |     self._ensure_connection(**conn_opts)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 433, in _ensure_connection
swirl1-8rc-app-1  |     return retry_over_time(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
swirl1-8rc-app-1  |     self.gen.throw(type, value, traceback)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
swirl1-8rc-app-1  |     raise ConnectionError(str(exc)) from exc
swirl1-8rc-app-1  | kombu.exceptions.OperationalError: [Errno 111] Connection refused
swirl1-8rc-app-1  | 2023-01-15 14:10:48,327 ERROR    Internal Server Error: /swirl/search/
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 30, in __call__
swirl1-8rc-app-1  |     return self.__value__
swirl1-8rc-app-1  | AttributeError: 'ChannelPromise' object has no attribute '__value__'
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | During handling of the above exception, another exception occurred:
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
swirl1-8rc-app-1  |     yield
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 433, in _ensure_connection
swirl1-8rc-app-1  |     return retry_over_time(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
swirl1-8rc-app-1  |     return fun(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 877, in _connection_factory
swirl1-8rc-app-1  |     self._connection = self._establish_connection()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 812, in _establish_connection
swirl1-8rc-app-1  |     conn = self.transport.establish_connection()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
swirl1-8rc-app-1  |     conn.connect()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 323, in connect
swirl1-8rc-app-1  |     self.transport.connect()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 129, in connect
swirl1-8rc-app-1  |     self._connect(self.host, self.port, self.connect_timeout)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 184, in _connect
swirl1-8rc-app-1  |     self.sock.connect(sa)
swirl1-8rc-app-1  | ConnectionRefusedError: [Errno 111] Connection refused
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | The above exception was the direct cause of the following exception:
swirl1-8rc-app-1  | 
swirl1-8rc-app-1  | Traceback (most recent call last):
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
swirl1-8rc-app-1  |     raise exc_info[1]
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 42, in inner
swirl1-8rc-app-1  |     response = await get_response(request)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
swirl1-8rc-app-1  |     response = await wrapped_callback(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 448, in __call__
swirl1-8rc-app-1  |     ret = await asyncio.wait_for(future, timeout=None)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
swirl1-8rc-app-1  |     return await fut
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 22, in run
swirl1-8rc-app-1  |     result = self.fn(*self.args, **self.kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 490, in thread_handler
swirl1-8rc-app-1  |     return func(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
swirl1-8rc-app-1  |     return view_func(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
swirl1-8rc-app-1  |     return self.dispatch(request, *args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
swirl1-8rc-app-1  |     response = self.handle_exception(exc)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
swirl1-8rc-app-1  |     self.raise_uncaught_exception(exc)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
swirl1-8rc-app-1  |     raise exc
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
swirl1-8rc-app-1  |     response = handler(request, *args, **kwargs)
swirl1-8rc-app-1  |   File "/app/swirl/views.py", line 191, in list
swirl1-8rc-app-1  |     search_task.delay(new_search.id)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 425, in delay
swirl1-8rc-app-1  |     return self.apply_async(args, kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 575, in apply_async
swirl1-8rc-app-1  |     return app.send_task(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 788, in send_task
swirl1-8rc-app-1  |     amqp.send_task_message(P, name, message, **options)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 510, in send_task_message
swirl1-8rc-app-1  |     ret = producer.publish(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
swirl1-8rc-app-1  |     return _publish(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 523, in _ensured
swirl1-8rc-app-1  |     return fun(*args, **kwargs)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 186, in _publish
swirl1-8rc-app-1  |     channel = self.channel
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 209, in _get_channel
swirl1-8rc-app-1  |     channel = self._channel = channel()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 32, in __call__
swirl1-8rc-app-1  |     value = self.__value__ = self.__contract__()
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 225, in <lambda>
swirl1-8rc-app-1  |     channel = ChannelPromise(lambda: connection.default_channel)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 895, in default_channel
swirl1-8rc-app-1  |     self._ensure_connection(**conn_opts)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 433, in _ensure_connection
swirl1-8rc-app-1  |     return retry_over_time(
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
swirl1-8rc-app-1  |     self.gen.throw(type, value, traceback)
swirl1-8rc-app-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
swirl1-8rc-app-1  |     raise ConnectionError(str(exc)) from exc
swirl1-8rc-app-1  | kombu.exceptions.OperationalError: [Errno 111] Connection refused
```

**Comment by sidprobstein** [comment]
Will investigate

**Comment by erikspears** [comment]
This is fixed in the latest Docker update to Swirl v. 1.8.1.  Closing out.
CC:  @sidprobstein
